In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["abc","pqr","xyz"],
    "marks":[77,98,90],
    "city":['pune','kolkata','mumbai']
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

  name  marks     city
0  abc     77     pune
1  pqr     98  kolkata
2  xyz     90   mumbai

In [5]:
df.to_csv('Sample.csv')

In [6]:
'''To avoid getting index reflect in csv use index=False after csv name'''
df.to_csv('Sample_withoutindex',index=False)

In [7]:
df.head(2)

  name  marks     city
0  abc     77     pune
1  pqr     98  kolkata

In [8]:
df.tail(2)

  name  marks     city
1  pqr     98  kolkata
2  xyz     90   mumbai

In [9]:
df1=pd.read_csv('Data.csv')

In [10]:
df1=pd.read_excel('Data.xlsx')

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\abhilasha\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\abhilasha\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
df1

   train no  speed     city
0      1234     77     pune
1      2345     98  kolkata
2      8789     90   mumbai

In [13]:
df1.to_csv('Data.csv',index=False)

In [14]:
df1

   train no  speed     city
0      1234     77     pune
1      2345     98  kolkata
2      8789     90   mumbai

In [15]:
'''creating random dataframe'''
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf

            0         1         2         3         4
0    0.879332  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4    0.812310  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [16]:
newdf.head()

          0         1         2         3         4
0  0.879332  0.416950  0.209199  0.848756  0.980273
1  0.757165  0.366722  0.098917  0.730611  0.210446
2  0.316732  0.543132  0.413761  0.346969  0.628194
3  0.359364  0.099661  0.751881  0.891777  0.394228
4  0.812310  0.396610  0.024178  0.693311  0.792909

In [17]:
type(newdf)

pandas.core.frame.DataFrame

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.514578    0.505477    0.509729    0.488253    0.489680
std      0.282199    0.292687    0.304401    0.281827    0.286137
min      0.001767    0.002341    0.002305    0.007179    0.002314
25%      0.264607    0.248330    0.242912    0.251045    0.252103
50%      0.511628    0.526965    0.501601    0.470532    0.473281
75%      0.767432    0.750530    0.789261    0.738969    0.729622
max      0.996496    0.999008    0.997374    0.997973    0.995509

In [19]:
newdf[0][0]='abc'

C:\Users\Abhilasha\AppData\Local\Temp\ipykernel_14308\2682602175.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]='abc'
C:\Users\Abhilasha\AppData\Local\Temp\ipykernel_14308\2682602175.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'abc' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]='abc'

In [20]:
newdf

            0         1         2         3         4
0         abc  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0         abc  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]>

In [23]:
newdf[0][0]=0.9

In [24]:
newdf

            0         1         2         3         4
0         0.9  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [25]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.224963  0.768485  0.819141  0.979902  0.692977
332  0.364927  0.324731  0.412655  0.930025  0.206937
331  0.345146  0.557056  0.935609  0.033537  0.547799
330  0.327737  0.616919  0.174034  0.039671  0.689398
329  0.073416  0.594044  0.930874  0.364316  0.927731
..        ...       ...       ...       ...       ...
4     0.81231  0.396610  0.024178  0.693311  0.792909
3    0.359364  0.099661  0.751881  0.891777  0.394228
2    0.316732  0.543132  0.413761  0.346969  0.628194
1    0.757165  0.366722  0.098917  0.730611  0.210446
0         0.9  0.416950  0.209199  0.848756  0.980273

[334 rows x 5 columns]

In [26]:
newdf.columns=list('ABCDE')

In [27]:
newdf

            A         B         C         D         E
0         0.9  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [28]:
newdf.loc[0,'A']=0

In [29]:
newdf.head(2)

          A         B         C         D         E
0         0  0.416950  0.209199  0.848756  0.980273
1  0.757165  0.366722  0.098917  0.730611  0.210446

In [30]:
newdf.loc[0,0]=0

In [31]:
newdf.head(2)

          A         B         C         D         E    0
0         0  0.416950  0.209199  0.848756  0.980273  0.0
1  0.757165  0.366722  0.098917  0.730611  0.210446  NaN

In [32]:
newdf.drop(0,axis=1)

            A         B         C         D         E
0           0  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [33]:
newdf.loc[[1,2],:]

          A         B         C         D         E   0
1  0.757165  0.366722  0.098917  0.730611  0.210446 NaN
2  0.316732  0.543132  0.413761  0.346969  0.628194 NaN

In [34]:
newdf=newdf.drop(0,axis=1)

In [35]:
newdf

            A         B         C         D         E
0           0  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [36]:
newdf.loc[0,'A']=8

In [37]:
'''filtering out'''
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
15   0.210422  0.996455  0.941184  0.656092  0.229786
16    0.28276  0.949799  0.265431  0.196442  0.079517
21   0.080841  0.130563  0.445023  0.694707  0.579056
23   0.252661  0.524480  0.833634  0.240584  0.713892
25   0.242958  0.956312  0.731561  0.864798  0.316328
..        ...       ...       ...       ...       ...
320  0.246195  0.820990  0.857802  0.438840  0.299866
324  0.212782  0.102228  0.206421  0.688327  0.459435
325  0.258736  0.855629  0.531156  0.263050  0.940096
329  0.073416  0.594044  0.930874  0.364316  0.927731
333  0.224963  0.768485  0.819141  0.979902  0.692977

[94 rows x 5 columns]

In [38]:
newdf.head(2)

          A         B         C         D         E
0         8  0.416950  0.209199  0.848756  0.980273
1  0.757165  0.366722  0.098917  0.730611  0.210446

In [39]:
newdf.iloc[0,4]

np.float64(0.9802726646483326)

In [40]:
newdf.iloc[[0,4],[1,2]]

         B         C
0  0.41695  0.209199
4  0.39661  0.024178

In [41]:
newdf

            A         B         C         D         E
0           8  0.416950  0.209199  0.848756  0.980273
1    0.757165  0.366722  0.098917  0.730611  0.210446
2    0.316732  0.543132  0.413761  0.346969  0.628194
3    0.359364  0.099661  0.751881  0.891777  0.394228
4     0.81231  0.396610  0.024178  0.693311  0.792909
..        ...       ...       ...       ...       ...
329  0.073416  0.594044  0.930874  0.364316  0.927731
330  0.327737  0.616919  0.174034  0.039671  0.689398
331  0.345146  0.557056  0.935609  0.033537  0.547799
332  0.364927  0.324731  0.412655  0.930025  0.206937
333  0.224963  0.768485  0.819141  0.979902  0.692977

[334 rows x 5 columns]

In [42]:
newdf.groupby('A')

In [43]:
df

  name  marks     city
0  abc     77     pune
1  pqr     98  kolkata
2  xyz     90   mumbai

In [45]:
df.groupby('name').size()

name
abc    1
pqr    1
xyz    1
dtype: int64

In [46]:
df.groupby('marks').min()

      name     city
marks
77     abc     pune
90     xyz   mumbai
98     pqr  kolkata

In [47]:
df.groupby('name').get_group('abc')

  name  marks  city
0  abc     77  pune

In [49]:
for name,group in df.groupby('name'):
    print("Group name:",group)
    print(name)
    print()

Group name:   name  marks  city
0  abc     77  pune
abc

Group name:   name  marks     city
1  pqr     98  kolkata
pqr

Group name:   name  marks    city
2  xyz     90  mumbai
xyz