In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["abc","pqr","xyz"],
    "marks":[77,98,90],
    "city":['pune','kolkata','mumbai']
}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

  name  marks     city
0  abc     77     pune
1  pqr     98  kolkata
2  xyz     90   mumbai

In [5]:
df.to_csv('Sample.csv')

In [6]:
'''To avoid getting index reflect in csv use index=False after csv name'''
df.to_csv('Sample_withoutindex',index=False)

In [7]:
df.head(2)

  name  marks     city
0  abc     77     pune
1  pqr     98  kolkata

In [8]:
df.tail(2)

  name  marks     city
1  pqr     98  kolkata
2  xyz     90   mumbai

In [9]:
df1=pd.read_csv('Data.csv')

In [10]:
df1=pd.read_excel('Data.xlsx')

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\abhilasha\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\abhilasha\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
df1

   train no  speed     city
0      1234     77     pune
1      2345     98  kolkata
2      8789     90   mumbai

In [13]:
df1.to_csv('Data.csv',index=False)

In [14]:
df1

   train no  speed     city
0      1234     77     pune
1      2345     98  kolkata
2      8789     90   mumbai

In [15]:
'''creating random dataframe'''
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf

            0         1         2         3         4
0    0.691590  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332  0.600720  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [16]:
newdf.head()

          0         1         2         3         4
0  0.691590  0.652229  0.104620  0.373874  0.507399
1  0.739157  0.345269  0.936830  0.670173  0.410486
2  0.247321  0.536070  0.281763  0.248138  0.583282
3  0.799371  0.325656  0.437658  0.031710  0.046342
4  0.225776  0.300580  0.820320  0.571831  0.494983

In [17]:
type(newdf)

pandas.core.frame.DataFrame

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.515045    0.493350    0.547840    0.511024    0.486678
std      0.282881    0.290594    0.280136    0.292416    0.277994
min      0.003029    0.000233    0.000568    0.005133    0.005095
25%      0.279487    0.240515    0.331232    0.257754    0.257143
50%      0.518629    0.487099    0.545613    0.506493    0.480772
75%      0.755822    0.734550    0.787326    0.770566    0.717172
max      0.997891    0.996564    0.997828    0.999653    0.995151

In [19]:
newdf[0][0]='abc'

C:\Users\Abhilasha\AppData\Local\Temp\ipykernel_17224\2682602175.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]='abc'
C:\Users\Abhilasha\AppData\Local\Temp\ipykernel_17224\2682602175.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'abc' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]='abc'

In [20]:
newdf

            0         1         2         3         4
0         abc  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0         abc  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]>

In [23]:
newdf[0][0]=0.9

In [24]:
newdf

            0         1         2         3         4
0         0.9  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [25]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.984803  0.846298  0.535132  0.116837  0.618903
332   0.60072  0.333599  0.354315  0.540111  0.870655
331  0.003029  0.266238  0.769921  0.874564  0.645581
330  0.759387  0.069086  0.170030  0.313903  0.517221
329  0.975803  0.886975  0.169840  0.053018  0.642451
..        ...       ...       ...       ...       ...
4    0.225776  0.300580  0.820320  0.571831  0.494983
3    0.799371  0.325656  0.437658  0.031710  0.046342
2    0.247321  0.536070  0.281763  0.248138  0.583282
1    0.739157  0.345269  0.936830  0.670173  0.410486
0         0.9  0.652229  0.104620  0.373874  0.507399

[334 rows x 5 columns]

In [26]:
newdf.columns=list('ABCDE')

In [27]:
newdf

            A         B         C         D         E
0         0.9  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [28]:
newdf.loc[0,'A']=0

In [29]:
newdf.head(2)

          A         B        C         D         E
0         0  0.652229  0.10462  0.373874  0.507399
1  0.739157  0.345269  0.93683  0.670173  0.410486

In [30]:
newdf.loc[0,0]=0

In [31]:
newdf.head(2)

          A         B        C         D         E    0
0         0  0.652229  0.10462  0.373874  0.507399  0.0
1  0.739157  0.345269  0.93683  0.670173  0.410486  NaN

In [32]:
newdf.drop(0,axis=1)

            A         B         C         D         E
0           0  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [33]:
newdf.loc[[1,2],:]

          A         B         C         D         E   0
1  0.739157  0.345269  0.936830  0.670173  0.410486 NaN
2  0.247321  0.536070  0.281763  0.248138  0.583282 NaN

In [34]:
newdf=newdf.drop(0,axis=1)

In [35]:
newdf

            A         B         C         D         E
0           0  0.652229  0.104620  0.373874  0.507399
1    0.739157  0.345269  0.936830  0.670173  0.410486
2    0.247321  0.536070  0.281763  0.248138  0.583282
3    0.799371  0.325656  0.437658  0.031710  0.046342
4    0.225776  0.300580  0.820320  0.571831  0.494983
..        ...       ...       ...       ...       ...
329  0.975803  0.886975  0.169840  0.053018  0.642451
330  0.759387  0.069086  0.170030  0.313903  0.517221
331  0.003029  0.266238  0.769921  0.874564  0.645581
332   0.60072  0.333599  0.354315  0.540111  0.870655
333  0.984803  0.846298  0.535132  0.116837  0.618903

[334 rows x 5 columns]

In [36]:
newdf.loc[0,'A']=8

In [38]:
'''filtering out'''
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
2    0.247321  0.536070  0.281763  0.248138  0.583282
4    0.225776  0.300580  0.820320  0.571831  0.494983
6    0.142797  0.268548  0.207803  0.922356  0.635851
11   0.201768  0.313237  0.571196  0.385361  0.251115
12   0.113225  0.489010  0.491227  0.445939  0.859188
..        ...       ...       ...       ...       ...
311  0.212249  0.748892  0.487035  0.682625  0.423201
313  0.283345  0.210695  0.984587  0.070337  0.340057
324  0.134361  0.539799  0.610497  0.929345  0.389126
328  0.263381  0.515689  0.904807  0.763933  0.747100
331  0.003029  0.266238  0.769921  0.874564  0.645581

[93 rows x 5 columns]

In [40]:
newdf.head(2)

          A         B        C         D         E
0         8  0.652229  0.10462  0.373874  0.507399
1  0.739157  0.345269  0.93683  0.670173  0.410486

In [39]:
newdf.iloc[0,4]

np.float64(0.5073990173003733)

In [42]:
newdf.iloc[[0,4],[1,2]]

          B        C
0  0.652229  0.10462
4  0.300580  0.82032